### ISSUE TITLE
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

### ISSUE THREAD

**Issue by vaibhavjnf** [SahilChachra/Video-Analytics-Dashboard#10]
![Capture](https://user-images.githubusercontent.com/15798711/187697918-bb2e2770-37d8-4799-95dd-9c685d60775c.PNG)
![error 1](https://user-images.githubusercontent.com/15798711/187697953-094a2698-2489-432b-82f6-1481c695ddb7.PNG)

**Comment by vaibhavjnf** [comment]
Hello please reply

**Comment by SahilChachra** [comment]
Duplicate issue. Already opened Issue #9 for same.

**Comment by spinxi** [comment]
Check [https://github.com/SahilChachra/Video-Analytics-Dashboard/issues/14](this)

**Comment by spinxi** [comment]
Check [this](https://github.com/SahilChachra/Video-Analytics-Dashboard/issues/14)
