### ISSUE TITLE
File missing in deep sort folder

### ISSUE THREAD

**Issue by protestToViolence** [SahilChachra/Video-Analytics-Dashboard#12]
Hello,
While running the code in my anaconda environment i found that in the deep_sort_pytorch/deep_sort/deep/checkpoint
a file named ckpt.t7 is missing which is giving error. Kindly fix it. I have to separately download it from another repo.
Thank you,

**Comment by SahilChachra** [comment]
I had already mentioned about this in the readme of the repo. I have provided seperate link for the same.

Do checkout READMEs of repos.

![image](https://user-images.githubusercontent.com/37156032/193458178-a63ca883-d982-404d-b8c6-ba4ad8be87ae.png)
