### ISSUE TITLE
Crop 1 image for every new object

### ISSUE THREAD

**Issue by spinxi** [SahilChachra/Video-Analytics-Dashboard#16]
Well I'm facing some issues bout cropping, when cropping is set to True, it does its job, but it exports detected objects from every frame, but I need to export 1 cropped image for every new car. for example if the first 3 second of video there is 1 car I need 1 crop, if there appears another car I need second 1 crop. Is there any suggestions how to make it workable , that would be interesting for everybody

**Comment by SahilChachra** [comment]
Saving cropped image code belongs to YoloV5. Feel free to experiment with Deepsort's output in save_crop's if condition to get cropped images only when new id pops up.
Thanks!
