### ISSUE TITLE
Ask questions

### ISSUE THREAD

**Issue by ahnuhxw** [SahilChachra/Video-Analytics-Dashboard#2]
Hello, what should I do if I want to display data in real time in the form of statistical chart，thanks

**Comment by SahilChachra** [comment]
Hey
Use can create a dictionary (with whatever data you want to plot, for eg time vs num of objects), convert it to DataFrame and pass it to Matplotlib or Seaborn to plot it. Checkout this link to plot graphs on streamlit in real time - https://docs.streamlit.io/library/api-reference/charts
