### ISSUE TITLE
.ckpt file

### ISSUE THREAD

**Issue by npq-thien** [SahilChachra/Video-Analytics-Dashboard#21]
I want to ask about this ckpt file. I didn't see it in the checkpoint folder.
Thank you
![image](https://user-images.githubusercontent.com/75383204/200741911-ed9647dd-e4cf-47e1-acd2-7b8574ec2745.png)

**Comment by SahilChachra** [comment]
If you go through the readme of repo, I have written few steps on How to use this repo. There I've mentioned the link to ckpt file which is to be downloaded from the given link and placed in the given path.

![Screenshot_20221109_102826](https://user-images.githubusercontent.com/37156032/200742610-2615ed7e-1564-46fc-9aac-73b1e1cca092.jpg)
