### ISSUE TITLE
CPU higher than GPU

### ISSUE THREAD

**Issue by mikahoy045** [SahilChachra/Video-Analytics-Dashboard#24]
Why the CPU usage higher than GPU (and fps too low) while already active GPU?
RTX 3070 8GB

**Comment by SahilChachra** [comment]
If it is possible, can you share a small clip/screen record while running the application? Or maybe few screenshots?

**Comment by mikahoy045** [comment]
Hi Sahil, 
this has a connection with issue #25.  I tried to build my custom yolov7 (based on yolov5x.pt) module clone from ultralytic (as of 1 February 2023), and the model running successfully. But when I run it has an error due to the outdated script in yolov5 here. So I try to train using yolov5 here but I get an error also, so I replace the whole yolov5 folder with the new updated one (since you can't get 2 versions of the yolov5 folder even with the different name together, you'll get module import error). 

the GPU use is normal by now (using updated yolov5) taking 90% of my GPU RAM, and only 50% of my CPU (Without SORT of course). So probably caused by that, probably you want to update the yolov5 with SORT.

**Comment by SahilChachra** [comment]
Okayy. Thanks.
I'll update the YoloV5 here in the repo in sometime so that we don't face such issues.
And I guess, since we are running torch model + Sort that too displaying that on Streamlit, it's taking a toll on the system usage.
I'll see how we can improve this going further.

**Comment by mikahoy045** [comment]
Sure, we can improve this.
