### ISSUE TITLE
Disable SORT in some RTMP

### ISSUE THREAD

**Issue by mikahoy045** [SahilChachra/Video-Analytics-Dashboard#25]
I have 3 RTMP link 
- water level
- traffic 1
- traffic 2

I want to use deep sort only for _traffic 1_ and _2_, while at _water level_ I don't need it.  How to achieve this? (I can duplicate the detect() but I don't know at which part to disable the Deep Sort).

**Comment by SahilChachra** [comment]
Hi
I'll check it out once and let you know.

**Comment by mikahoy045** [comment]
Solved with issue #24
