### ISSUE TITLE
Nothing on the screen

### ISSUE THREAD

**Issue by joel5638** [SahilChachra/Video-Analytics-Dashboard#3]
I have done exactly the same steps mentioned in the readme.
I see a blank screen(dashboard).

How do i execute the yolo weights to see through webcam or any video. Please see the screenshot of my screen.
Nothing opens up.
![Screenshot from 2022-07-14 18-11-41](https://user-images.githubusercontent.com/38422983/178984785-765b07f0-75f3-4a11-a33f-e2babd60f7c9.png)

**Comment by SahilChachra** [comment]
I can see the output of the webcam and local video file as well. Please check the logs where you ran streamlit run app.py.
Also, please clone the repository again. I've changed the path of yolov5s.pt file and also mentioned how to add DeepSort checkpoint file.

![Screenshot from 2022-07-14 18-21-38](https://user-images.githubusercontent.com/37156032/178987703-f34d22ce-0f01-4a3e-bea3-eed7db24496c.png)
![Screenshot from 2022-07-14 18-27-18](https://user-images.githubusercontent.com/37156032/178987704-640045a0-8d8a-4231-b72c-3f22cf0de730.png)

**Comment by joel5638** [comment]
Local video works perfectly fine. But the webcam doesnt seem to work.
![Screenshot from 2022-07-15 11-39-33](https://user-images.githubusercontent.com/38422983/179162165-c16d7831-da8b-4ad3-926e-f1cfc34022de.png)

**Comment by SahilChachra** [comment]
Kindly check if you have USB camera connected. Also confirm that your device assigns '0' to the webcam you are using and webcam is working fine by another application and the webcam is not being used by another application before running this application.

If it is some another number, please update the source variable in app.py line 162
`detect(weights="yolov5s.pt", source='0', stframe=stframe, ...`
Here in source, assign the number your device is assigning to your webcam

**Comment by joel5638** [comment]
its a laptop and its assigned with 0 But still doesnt work. Im just checking

**Comment by SahilChachra** [comment]
Check if you can use your webcam by a simple OpenCv program which reads image from webcam and displays it. If it is working in this program then it'll run in streamlit as well

**Comment by joel5638** [comment]
Works with source as 1. Perfect man. Great work.

**Comment by SahilChachra** [comment]
Thanks 🥳
