### ISSUE TITLE
AttributeError: module 'streamlit' has no attribute 'columns'

### ISSUE THREAD

**Issue by joel5638** [SahilChachra/Video-Analytics-Dashboard#4]
Now while trying to track objects I get this error.
![Screenshot from 2022-07-14 18-16-54](https://user-images.githubusercontent.com/38422983/178985840-20e1e4fe-bd06-4df8-9af1-6421c8465074.png)

**Comment by SahilChachra** [comment]
Please check the version of streamlit installed. For me it's running without any errors. Just cloned the repo and tested. I am using streamlit version==1.7.0
![Screenshot from 2022-07-14 18-21-38](https://user-images.githubusercontent.com/37156032/178986587-2e21a68b-67d4-4b96-a9cf-c2854f1d180d.png)

**Comment by joel5638** [comment]
perfect. issue resolved
